@BookStoreApp.Api_HostAddress = https://localhost:7168/authors
@BookStoreApp.Api_AccessToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InVzZXIiLCJqdGkiOiJkOTM5MDVmYi05NTU0LTRmZmMtOGM4My0wOGExNjEyNWUyM2UiLCJ1aWQiOiIyMUYwMTQyNy0yNjIyLTQzQzgtQjVGMy1CQkQ1OERBMTkwQzIiLCJlbWFpbCI6InVzZXJAdXNlci5jb20iLCJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1lIjoidXNlckB1c2VyLmNvbSIsInJvbGUiOiJVc2VyIiwiZXhwIjoxNzM0MDE4MjQwLCJpc3MiOiJCb29rU3RvcmVBcGkiLCJhdWQiOiJCb29rU3RvcmVBcGlDbGllbnQifQ.n-dHYN7ucw_t5CY2xy27w-YW_LUbzJrs0LVxvBnxUew

GET {{BookStoreApp.Api_HostAddress}}
Accept: application/json
Authorization: Bearer {{BookStoreApp.Api_AccessToken}}

###
